name: Alerta CI - Python

on:
  push:
    branches: [ main ]

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar programa
        run: python main.py

      - name: Enviar alerta a ntfy.sh
        run: |
          curl -d "¡Hola Mundo en Python! Código subido a la rama main con éxito. Angel Sanchez 2025-1039" ntfy.sh/devops-itla

      